on:
  push:
    tags:
      - '*'
jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub REF
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          NAME_TAG: "foo.azurecr.io/bar-baz:${${GITHUB_REF#refs/tags/}#v}"
        run: |
          echo "$GITHUB_REF"
          echo "${${GITHUB_REF#refs/tags/}#v}"
          echo "$NAME_TAG"
